/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codeday;

/**
 *
 * @author Kirjsten
 */
public class DevelopGUI extends javax.swing.JFrame {

    /**
     * Creates new form DevelopGUI
     */
    public DevelopGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleTextfeild = new javax.swing.JLabel();
        createDreamBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleTextfeild.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Textfeild Empty (white-black boarder).png"))); // NOI18N
        getContentPane().add(titleTextfeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 340, 50));

        createDreamBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/createProjectbackground.png"))); // NOI18N
        getContentPane().add(createDreamBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-340, -100, -1, 760));

        setSize(new java.awt.Dimension(772, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createDreamBackground;
    private javax.swing.JLabel titleTextfeild;
    // End of variables declaration//GEN-END:variables
}
