/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codeday;

/**
 *
 * @author Kirjsten
 */
public class DreamGUI extends javax.swing.JFrame {

    /**
     * Creates new form DreamGUI
     */
    public DreamGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textfeildTite = new javax.swing.JLabel();
        createDreamBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textfeildTite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Textfeild Empty (white-black boarder).png"))); // NOI18N
        getContentPane().add(textfeildTite, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 340, 60));

        createDreamBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/createdreambackground.png"))); // NOI18N
        getContentPane().add(createDreamBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-310, -10, 1180, 580));

        setSize(new java.awt.Dimension(801, 528));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createDreamBackground;
    private javax.swing.JLabel textfeildTite;
    // End of variables declaration//GEN-END:variables
}
