/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codeday;

import java.awt.Cursor;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author Kirjsten
 */
public class DevelopListGUI extends javax.swing.JFrame {

    /**
     * Creates new form DevelopListGUI
     */
    public DevelopListGUI() {
        initComponents();
        changeIcon();
        //get the list of users projects
        projectTitle1.setText("");
        projectTitle2.setText("");
        projectTitle3.setText("");
        projectTitle4.setText("");
        projectTitle5.setText("");
        projectTitle6.setText("");
    }
     public void changeIcon()
    {
        URL url = getClass().getResource("/AppPackage/MiniIcon.png");
         if (url != null) 
         {
            ImageIcon icon = new ImageIcon(url);
            Image image = icon.getImage();
            this.setIconImage(image);
        } else {
            System.err.println("Couldn't find icon file");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectTitle1 = new javax.swing.JLabel();
        projectTitle2 = new javax.swing.JLabel();
        projectTitle3 = new javax.swing.JLabel();
        projectTitle4 = new javax.swing.JLabel();
        projectTitle5 = new javax.swing.JLabel();
        projectTitle6 = new javax.swing.JLabel();
        developListBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        projectTitle1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        projectTitle1.setForeground(new java.awt.Color(255, 51, 51));
        projectTitle1.setText("Project Title 1");
        projectTitle1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projectTitle1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                projectTitle1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                projectTitle1MouseExited(evt);
            }
        });
        getContentPane().add(projectTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 190, 30));

        projectTitle2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        projectTitle2.setForeground(new java.awt.Color(255, 51, 51));
        projectTitle2.setText("Project Title 2");
        projectTitle2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projectTitle2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                projectTitle2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                projectTitle2MouseExited(evt);
            }
        });
        getContentPane().add(projectTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 160, 30));

        projectTitle3.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        projectTitle3.setForeground(new java.awt.Color(255, 51, 51));
        projectTitle3.setText("Project Title 3");
        projectTitle3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projectTitle3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                projectTitle3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                projectTitle3MouseExited(evt);
            }
        });
        getContentPane().add(projectTitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 170, 40));

        projectTitle4.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        projectTitle4.setForeground(new java.awt.Color(255, 51, 51));
        projectTitle4.setText("Project Title 4 ");
        projectTitle4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projectTitle4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                projectTitle4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                projectTitle4MouseExited(evt);
            }
        });
        getContentPane().add(projectTitle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 160, 30));

        projectTitle5.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        projectTitle5.setForeground(new java.awt.Color(255, 51, 51));
        projectTitle5.setText("Project Title 5");
        projectTitle5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projectTitle5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                projectTitle5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                projectTitle5MouseExited(evt);
            }
        });
        getContentPane().add(projectTitle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 160, 30));

        projectTitle6.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        projectTitle6.setForeground(new java.awt.Color(255, 51, 51));
        projectTitle6.setText("Project Title 6");
        projectTitle6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projectTitle6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                projectTitle6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                projectTitle6MouseExited(evt);
            }
        });
        getContentPane().add(projectTitle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 160, 30));

        developListBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/myProjectsBackground.png"))); // NOI18N
        getContentPane().add(developListBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-370, -100, 1360, 770));

        setSize(new java.awt.Dimension(693, 534));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void projectTitle1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectTitle1MouseEntered
        //change mouse cursor to hand pointer
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_projectTitle1MouseEntered

    private void projectTitle2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectTitle2MouseEntered
        //change mouse cursor to hand pointer
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_projectTitle2MouseEntered

    private void projectTitle3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectTitle3MouseEntered
        //change mouse cursor to hand pointer
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_projectTitle3MouseEntered

    private void projectTitle4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectTitle4MouseEntered
        //change mouse cursor to hand pointer
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_projectTitle4MouseEntered

    private void projectTitle5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectTitle5MouseEntered
        //change mouse cursor to hand pointer
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_projectTitle5MouseEntered

    private void projectTitle6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectTitle6MouseEntered
        //change mouse cursor to hand pointer
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_projectTitle6MouseEntered

    private void projectTitle1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectTitle1MouseExited
       //change mouse cursor to default cursor
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_projectTitle1MouseExited

    private void projectTitle2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectTitle2MouseExited
       //change mouse cursor to default cursor
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_projectTitle2MouseExited

    private void projectTitle3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectTitle3MouseExited
        //change mouse cursor to default cursor
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_projectTitle3MouseExited

    private void projectTitle4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectTitle4MouseExited
     //change mouse cursor to default cursor
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_projectTitle4MouseExited

    private void projectTitle5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectTitle5MouseExited
       //change mouse cursor to default cursor
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_projectTitle5MouseExited

    private void projectTitle6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectTitle6MouseExited
       //change mouse cursor to default cursor
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_projectTitle6MouseExited

    private void projectTitle1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectTitle1MouseClicked
        //Open DevelopEditGUI
        //user can edit there project
         new DevelopEditGUI().setVisible(true);
    }//GEN-LAST:event_projectTitle1MouseClicked

    private void projectTitle2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectTitle2MouseClicked
       //Open DevelopEditGUI
        //user can edit there project
         new DevelopEditGUI().setVisible(true);
    }//GEN-LAST:event_projectTitle2MouseClicked

    private void projectTitle3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectTitle3MouseClicked
        //Open DevelopEditGUI
        //user can edit there project
         new DevelopEditGUI().setVisible(true);
    }//GEN-LAST:event_projectTitle3MouseClicked

    private void projectTitle4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectTitle4MouseClicked
       //Open DevelopEditGUI
        //user can edit there project
         new DevelopEditGUI().setVisible(true);
    }//GEN-LAST:event_projectTitle4MouseClicked

    private void projectTitle5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectTitle5MouseClicked
        //Open DevelopEditGUI
        //user can edit there project
         new DevelopEditGUI().setVisible(true);
    }//GEN-LAST:event_projectTitle5MouseClicked

    private void projectTitle6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectTitle6MouseClicked
       //Open DevelopEditGUI
        //user can edit there project
         new DevelopEditGUI().setVisible(true);
    }//GEN-LAST:event_projectTitle6MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel developListBackground;
    private javax.swing.JLabel projectTitle1;
    private javax.swing.JLabel projectTitle2;
    private javax.swing.JLabel projectTitle3;
    private javax.swing.JLabel projectTitle4;
    private javax.swing.JLabel projectTitle5;
    private javax.swing.JLabel projectTitle6;
    // End of variables declaration//GEN-END:variables
}
