/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codeday;

import java.awt.Cursor;
import javax.swing.JOptionPane;

/**
 *
 * @author Kirjsten
 */
public class DevelopEditGUI extends javax.swing.JFrame {

    /**
     * Creates new form DevelopEditGUI
     */
    public DevelopEditGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        developTitle = new javax.swing.JLabel();
        tagPane = new javax.swing.JScrollPane();
        tags = new javax.swing.JTextArea();
        developPane = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        doneButton = new javax.swing.JLabel();
        developEditBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        developTitle.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        developTitle.setForeground(new java.awt.Color(255, 255, 255));
        developTitle.setText("Develop Title");
        getContentPane().add(developTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 230, 50));

        tagPane.setBorder(null);

        tags.setColumns(20);
        tags.setRows(5);
        tags.setText("Tags\nExample Tagging:\n\nbeauty, heat, funny");
        tags.setBorder(null);
        tags.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tagsMouseClicked(evt);
            }
        });
        tagPane.setViewportView(tags);

        getContentPane().add(tagPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 230, 90));

        developPane.setBorder(null);

        description.setColumns(20);
        description.setRows(5);
        description.setText("Description...");
        description.setBorder(null);
        description.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descriptionMouseClicked(evt);
            }
        });
        developPane.setViewportView(description);

        getContentPane().add(developPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 380, 310));

        doneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/DevelopEditGUI/RedDoneButton.png"))); // NOI18N
        doneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doneButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                doneButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                doneButtonMouseExited(evt);
            }
        });
        getContentPane().add(doneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 180, -1));

        developEditBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/DevelopEditGUI/DevelopEditGUIBackground.png"))); // NOI18N
        getContentPane().add(developEditBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-340, -130, 1360, 770));

        setSize(new java.awt.Dimension(735, 486));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void doneButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneButtonMouseClicked
        //save changes from textfeilds in panes
        
        //save function before save message
        JOptionPane.showMessageDialog(null,"Changes Saved");
        dispose();
    }//GEN-LAST:event_doneButtonMouseClicked

    private void doneButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneButtonMouseEntered
        //changes mouse cursor to hand pointer
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_doneButtonMouseEntered

    private void doneButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneButtonMouseExited
        //changes mouse cursor to default pointer
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_doneButtonMouseExited

    private void tagsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tagsMouseClicked
        //clears box when clicked
        tags.setText("");
    }//GEN-LAST:event_tagsMouseClicked

    private void descriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descriptionMouseClicked
        //clears box when clicked
        description.setText("");
    }//GEN-LAST:event_descriptionMouseClicked

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea description;
    private javax.swing.JLabel developEditBackground;
    private javax.swing.JScrollPane developPane;
    private javax.swing.JLabel developTitle;
    private javax.swing.JLabel doneButton;
    private javax.swing.JScrollPane tagPane;
    private javax.swing.JTextArea tags;
    // End of variables declaration//GEN-END:variables
}
