/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codeday;

import java.awt.Cursor;
import javax.swing.JOptionPane;

/**
 *
 * @author Kirjsten
 */
public class DreamEditGUI extends javax.swing.JFrame {

    /**
     * Creates new form DreamEditGUI
     */
    public DreamEditGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dreamTitle = new javax.swing.JLabel();
        dreamPane = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        tagPane = new javax.swing.JScrollPane();
        tags = new javax.swing.JTextArea();
        doneButton = new javax.swing.JLabel();
        dreamEditBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dreamTitle.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        dreamTitle.setForeground(new java.awt.Color(255, 255, 255));
        dreamTitle.setText("Dream Title");
        getContentPane().add(dreamTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 200, 40));

        dreamPane.setBorder(null);

        description.setColumns(20);
        description.setRows(5);
        description.setText("Tags\nExample Tagging:\n\nbeauty, heat, funny");
        description.setBorder(null);
        dreamPane.setViewportView(description);

        getContentPane().add(dreamPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 230, 90));

        tagPane.setBorder(null);

        tags.setColumns(20);
        tags.setRows(5);
        tags.setText("Description...");
        tags.setBorder(null);
        tagPane.setViewportView(tags);

        getContentPane().add(tagPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 380, 310));

        doneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/DreamEditGUI/Blue Done Button.png"))); // NOI18N
        doneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doneButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                doneButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                doneButtonMouseExited(evt);
            }
        });
        getContentPane().add(doneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 180, -1));

        dreamEditBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/DreamEditGUI/DreamEditGUIBackground.png"))); // NOI18N
        getContentPane().add(dreamEditBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-340, -130, 1360, 770));

        setSize(new java.awt.Dimension(764, 476));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void doneButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneButtonMouseClicked
        //saves changes from the textfeilds in the panes
        
        //save function before save message
        JOptionPane.showMessageDialog(null,"Changes Saved");
        dispose();
    }//GEN-LAST:event_doneButtonMouseClicked

    private void doneButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneButtonMouseEntered
        //make cursor hand pointer
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_doneButtonMouseEntered

    private void doneButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneButtonMouseExited
        //make cursor default pointer
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_doneButtonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea description;
    private javax.swing.JLabel doneButton;
    private javax.swing.JLabel dreamEditBackground;
    private javax.swing.JScrollPane dreamPane;
    private javax.swing.JLabel dreamTitle;
    private javax.swing.JScrollPane tagPane;
    private javax.swing.JTextArea tags;
    // End of variables declaration//GEN-END:variables
}
