/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codeday;

import java.awt.Cursor;
import java.awt.Image;
import java.io.*;
import java.net.URL;
import java.util.Scanner;
import javax.swing.ImageIcon;

/**
 *
 * @author Kirjsten
 */
public class RegisterGUI extends javax.swing.JFrame {
    private Person person;
    /**
     * Creates new form RegisterGUI
     */
    public RegisterGUI() {
        initComponents();
        changeIcon();
         person = new Person();

    }
     public void changeIcon()
    {
        URL url = getClass().getResource("/AppPackage/MiniIcon.png");
         if (url != null) 
         {
            ImageIcon icon = new ImageIcon(url);
            Image image = icon.getImage();
            this.setIconImage(image);
        } else {
            System.err.println("Couldn't find icon file");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textfeildUsername = new javax.swing.JTextField();
        usernameTextImage = new javax.swing.JLabel();
        textfeildName = new javax.swing.JTextField();
        nameTextImage = new javax.swing.JLabel();
        textfeildPassword = new javax.swing.JTextField();
        passwordTextImage = new javax.swing.JLabel();
        textfeildReenterPassword = new javax.swing.JTextField();
        reenterPasswordTextImage = new javax.swing.JLabel();
        textfeildEmail = new javax.swing.JTextField();
        emailTextImage = new javax.swing.JLabel();
        goButton = new javax.swing.JLabel();
        registerBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textfeildUsername.setText("Username");
        textfeildUsername.setBorder(null);
        textfeildUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textfeildUsernameMouseClicked(evt);
            }
        });
        textfeildUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfeildUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(textfeildUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 320, 30));

        usernameTextImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Textfeild Empty (white-black boarder).png"))); // NOI18N
        getContentPane().add(usernameTextImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 340, 50));

        textfeildName.setText("First/Last Name");
        textfeildName.setBorder(null);
        textfeildName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textfeildNameMouseClicked(evt);
            }
        });
        textfeildName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfeildNameActionPerformed(evt);
            }
        });
        getContentPane().add(textfeildName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 320, 30));

        nameTextImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Textfeild Empty (white-black boarder).png"))); // NOI18N
        getContentPane().add(nameTextImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        textfeildPassword.setText("Password");
        textfeildPassword.setBorder(null);
        textfeildPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textfeildPasswordMouseClicked(evt);
            }
        });
        textfeildPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfeildPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(textfeildPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 320, 30));

        passwordTextImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Textfeild Empty (white-black boarder).png"))); // NOI18N
        passwordTextImage.setText("    ");
        getContentPane().add(passwordTextImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 340, 50));

        textfeildReenterPassword.setText("Re-Enter Password");
        textfeildReenterPassword.setBorder(null);
        textfeildReenterPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textfeildReenterPasswordMouseClicked(evt);
            }
        });
        textfeildReenterPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfeildReenterPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(textfeildReenterPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 320, 30));

        reenterPasswordTextImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Textfeild Empty (white-black boarder).png"))); // NOI18N
        getContentPane().add(reenterPasswordTextImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 340, 50));

        textfeildEmail.setText("Email");
        textfeildEmail.setBorder(null);
        textfeildEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textfeildEmailMouseClicked(evt);
            }
        });
        textfeildEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfeildEmailActionPerformed(evt);
            }
        });
        getContentPane().add(textfeildEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 320, 30));

        emailTextImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Textfeild Empty (white-black boarder).png"))); // NOI18N
        getContentPane().add(emailTextImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 340, 50));

        goButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Register/GO! Button.png"))); // NOI18N
        goButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                goButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                goButtonMouseExited(evt);
            }
        });
        getContentPane().add(goButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 160, 60));

        registerBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Register/Register Page Background.png"))); // NOI18N
        getContentPane().add(registerBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-410, -110, 1360, 770));

        setSize(new java.awt.Dimension(638, 553));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void goButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goButtonMouseEntered
        //change mouse to hand pointer
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_goButtonMouseEntered

    private void goButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goButtonMouseExited
        //change mouse to normal pointer
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_goButtonMouseExited

    private void goButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goButtonMouseClicked
        //bring user question page
        person.setUserName(textfeildUsername.getText());
        person.setName(textfeildName.getText());
        person.setPassword(textfeildPassword.getText());
        person.setEmail(textfeildEmail.getText());
        person.setPerson();
        dispose();
        QuestionGUI question = new QuestionGUI(person);
        question.setVisible(true);
    }//GEN-LAST:event_goButtonMouseClicked

    private void textfeildNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfeildNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfeildNameActionPerformed

    private void textfeildPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfeildPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfeildPasswordActionPerformed

    private void textfeildReenterPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfeildReenterPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfeildReenterPasswordActionPerformed

    private void textfeildEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfeildEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfeildEmailActionPerformed

    private void textfeildUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfeildUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfeildUsernameActionPerformed

    private void textfeildUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textfeildUsernameMouseClicked
        //make textfeild null
        textfeildUsername.setText("");
        person.setUserName(textfeildUsername.getText());
    }//GEN-LAST:event_textfeildUsernameMouseClicked

    private void textfeildNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textfeildNameMouseClicked
        //make textfeild null
        textfeildName.setText("");
    }//GEN-LAST:event_textfeildNameMouseClicked

    private void textfeildPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textfeildPasswordMouseClicked
        //make textfeild null
        textfeildPassword.setText("");
    }//GEN-LAST:event_textfeildPasswordMouseClicked

    private void textfeildReenterPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textfeildReenterPasswordMouseClicked
        //make textfeild null
        textfeildReenterPassword.setText("");
    }//GEN-LAST:event_textfeildReenterPasswordMouseClicked

    private void textfeildEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textfeildEmailMouseClicked
        //make textfeild null
        textfeildEmail.setText("");
    }//GEN-LAST:event_textfeildEmailMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailTextImage;
    private javax.swing.JLabel goButton;
    private javax.swing.JLabel nameTextImage;
    private javax.swing.JLabel passwordTextImage;
    private javax.swing.JLabel reenterPasswordTextImage;
    private javax.swing.JLabel registerBackground;
    private javax.swing.JTextField textfeildEmail;
    private javax.swing.JTextField textfeildName;
    private javax.swing.JTextField textfeildPassword;
    private javax.swing.JTextField textfeildReenterPassword;
    private javax.swing.JTextField textfeildUsername;
    private javax.swing.JLabel usernameTextImage;
    // End of variables declaration//GEN-END:variables
}
